export const Weapons = [
  { nev: 'Tőr', kocka: '1d4', props: 'Concealable, Piercing, Throwable' },
  { nev: 'Pálca', kocka: '1d4', props: 'Concealable, Reach' },
  { nev: 'Ostor', kocka: '1d4', props: 'Reach, Concealable, Sweep' },
  { nev: 'Kard', kocka: '1d6', props: 'Piercing, Slashing' },
  {
    nev: 'Hosszúkard',
    kocka: '1d6',
    props: 'Bulky, Piercing, Slashing, Reach',
  },
  { nev: 'Rapír', kocka: '1d6', props: 'Piercing, Counter' },
  { nev: 'Szablya', kocka: '1d6', props: 'Slashing, Sweep' },
  { nev: 'Fejsze', kocka: '1d6', props: 'Slashing, Throwable' },
  { nev: 'Csatabárd', kocka: '1d8', props: 'Bulky, Slashing, Brutal' },
  { nev: 'Buzogány', kocka: '1d6', props: 'Bludgeoning, Sweep' },
  { nev: 'Lándzsa', kocka: '1d6', props: 'Reach, Piercing, Throwable' },
  { nev: 'Acél öklok', kocka: '2d4', props: 'Bludgeoning, Counter' },
  { nev: 'Kalapács', kocka: '1d6', props: 'Bludgeoning, Throwable' },
  { nev: 'Pöröly', kocka: '1d8', props: 'Bulky, Bludgeoning' },
  { nev: 'Fokos', kocka: '1d6', props: 'Bludgeoning, Slashing, Reach' },
  { nev: 'Íj', kocka: '1d10', props: 'Reload, Bulky, Range 10' },
  { nev: 'Számszeríj', kocka: '1d10', props: 'Reload, Bulky, Range 10' },
  {
    nev: 'Pisztoly',
    kocka: '1d12',
    props: 'Reload, Concealable, Piercing, Range 5',
  },
  {
    nev: 'Karabély',
    kocka: '1d12',
    props: 'Reload, Bulky, Piercing, Range 15',
  },
  { nev: 'Kézi ágyú', kocka: '3d6', props: 'Reload, Bulky, Blast, Range 10' },
  {
    nev: 'Kézi ballliszta',
    kocka: '1d20',
    props: 'Reload, Bulky, Brutal, Range 15',
  },
];
