export const Targyak = [
  { nev: 'Selyem', desc: 'Egy selyem szövetdarab' },
  { nev: 'Nyíl', desc: 'Egyetlen nyíl, obszidián heggyel' },
  { nev: 'Griff szobor', desc: 'Egy bronz szobor egy griffről' },
  { nev: 'Zafíros láda', desc: 'Egy erős láda tele zafírokkal' },
  { nev: 'Rothadó hús', desc: 'Egy rothadó vadkan húsdarab' },
  { nev: 'Szentelt víz', desc: 'Egy nagy üvegedény szentelt vízzel' },
  { nev: 'Törött kard', desc: 'Egy törött acél kard' },
  { nev: 'Tiszta ruhák', desc: 'Egy szépen összehajtott, tiszta ruhakészlet' },
  { nev: 'Rubinos gyűrű', desc: 'Egy arany gyűrű rubinnal' },
  { nev: 'Hamis okmány', desc: 'Egy hamisított okmány' },
  { nev: 'Szakadt köpeny', desc: 'Egy szakadt kék köpeny' },
  {
    nev: 'Kenyér és sajt',
    desc: 'Egy darab kenyér és sajt, ruhába csomagolva',
  },
  { nev: 'Jáde', desc: 'Egy marék jáde' },
  { nev: 'Sörös hordó', desc: 'Egy kis fából készült hordó tele sörrel' },
  { nev: 'Kis könyv', desc: 'Egy kis bőr kötésű könyv' },
  { nev: 'Rejtett üzenet', desc: 'Egy üres pergamen, rejtett üzenettel' },
  { nev: 'Hamu edény', desc: 'Egy nagy kő edény hamuval' },
  {
    nev: 'Rúnás korong',
    desc: 'Egy kerámia korong, melynek felületére egyetlen rúna van karcolva',
  },
  { nev: 'Dohányos zsák', desc: 'Egy kis selyem zsák dohánnyal' },
  { nev: 'Levendulás zsák', desc: 'Egy bőrzsák szárított levendulával' },
  { nev: 'Napérme', desc: 'Egy ezüst érme, rajta Nap szimbólummal' },
  { nev: 'Zöld üvegszem', desc: 'Egy zöld üvegszem' },
  { nev: 'Megégett fa', desc: 'Egy megégett fa hasáb' },
  { nev: 'Kalandor napló', desc: 'Egy kalandor bőr kötésű naplója' },
  { nev: 'Üveg bor', desc: 'Egy üveg bor' },
  { nev: 'Piros ing', desc: 'Egy piros ing' },
  { nev: 'Fa evőeszköz', desc: 'Egy fa evőeszközkészlet' },
  { nev: 'Vas pálca', desc: 'Egy vékony vas pálca' },
  { nev: 'Névsor', desc: 'Egy pergamen egy listával, amely neveket tartalmaz' },
  { nev: 'Fehér kréta', desc: 'Egy marék fehér kréta' },
  { nev: 'Réz kulcs', desc: 'Egy réz kulcs' },
  {
    nev: 'Kerámiadarabos zsák',
    desc: 'Egy bőrzsák, tele éles kerámiadarabokkal',
  },
  { nev: 'Durva térkép', desc: 'Egy durván megrajzolt térkép a környékről' },
  { nev: 'Kötélköteg', desc: 'Egy kusza köteg kötél' },
  { nev: 'Széndarab', desc: 'Egy nagy darab szén' },
  { nev: 'Mézes üveg', desc: 'Egy üveges flaskában méz' },
  {
    nev: 'Szent szimbólum',
    desc: 'Egy megszentelt szimbólum egy ismeretlen istenhez',
  },
  {
    nev: 'Sárkány festmény',
    desc: 'Egy torzított réz festmény egy sárkányról',
  },
  { nev: 'Vámpír vér', desc: 'Egy üvegviolában vámpír vér' },
  { nev: 'Zsineg horgokkal', desc: 'Egy vékony zsineg horgokkal' },
  { nev: 'Kék gyertya', desc: 'Egy kék gyertya' },
  { nev: 'Réz szemüveg', desc: 'Egy mocskos réz szemüveg' },
  { nev: 'Acél zár', desc: 'Egy acéls zár' },
  { nev: 'Piros dobókocka', desc: 'Egy piros húszoldalú dobókocka' },
  { nev: 'Bőr hátizsák', desc: 'Egy barna bőr hátizsák' },
  { nev: 'Fekete kardöv', desc: 'Egy fekete bőr kardöv' },
  { nev: 'Játékkártyák', desc: 'Egy készlet játékkártya' },
  {
    nev: 'Négyzetes pergamen',
    desc: 'Egy összegyűrt pergamen, amelyen egy centi nagyságú négyzetek találhatók',
  },
  {
    nev: 'Farkasos csempe',
    desc: 'Egy kerámia csempe egy farkas ábrázolásával',
  },
  { nev: 'Ezüst kesztyű', desc: 'Egy ezüst kesztyű, hat ujjal' },
  { nev: 'Kő maszk', desc: 'Egy kő maszk' },
  { nev: 'Bányászkalapács', desc: 'Egy acél bányászkalapács és lapát' },
  { nev: 'Halott patkányok', desc: 'Egy zsák halott patkányokkal' },
  { nev: 'Márvány napóra', desc: 'Egy márvány napóra' },
  {
    nev: 'Varázslatos pergamen',
    desc: 'Egy papírdarab egy ismeretlen varázslatról',
  },
  { nev: 'Farkasbőr öv', desc: 'Egy öv egy farkas bőréből' },
  {
    nev: 'Fogakkal teli tartály',
    desc: 'Egy réz tartály, amely emberi fogakat tart',
  },
  { nev: 'Réz fa', desc: 'Egy bőrzsák egy réz fával' },
  { nev: 'Csontcsomó', desc: 'Egy kis csontokból készült csomó' },
  { nev: 'Rozsdás bilincsek', desc: 'Egy rozsdás bilincs készlet' },
  { nev: 'Olajtartó', desc: 'Egy fa olajtartó' },
  { nev: 'Tigris fog', desc: 'Egy tigris fog' },
  { nev: 'Disznó agyar', desc: 'Gyuri kitörött foga' },
];
